### ISSUE TITLE
AssertionError: 27900 contigs found in file '../../TestData/Assemblies/S1_scaffolds.faa' were not found in assembly_file '../../TestData/Assemblies/S1_scaffolds.fasta

### ISSUE THREAD

**Issue by jolespin** [genotoul-bioinfo/Binette#35]
I was having some issues with the protein argument you've added.  Took a dive into the source code but wanted to post here too.

```
(/home/ec2-user/SageMaker/efs/sandbox/sandbox/conda_environments/jolespin/sagemaker/VEBA-binning-prokaryotic_env-dev) [ec2-user@ip-172-16-58-245 test-binette]$ binette -b ../test-semibin2/binning_wrapper_output/scaffolds_to_bins.tsv ../test-metadecoder/binning_wrapper_output_metadecoder/scaffolds_to_bins.tsv ../test-metacoag/binning_wrapper_output_metacaog/scaffolds_to_bins.tsv -c ../../TestData/Assemblies/S1_scaffolds.fasta -p -c ../../TestData/Assemblies/S1_scaffolds.faa -t 4 -o binette_output/ --checkm2_db /home/ec2-user/SageMaker/s3/newatlantis-raw-veba-db-prod/VDB_v8.1/Classify/CheckM2/uniref100.KO.1.dmnd
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/efs/sandbox/sandbox/conda_environments/jolespin/sagemaker/VEBA-binning-prokaryotic_env-dev/bin/binette", line 10, in <module>
    sys.exit(main())
  File "/home/ec2-user/SageMaker/efs/sandbox/sandbox/conda_environments/jolespin/sagemaker/VEBA-binning-prokaryotic_env-dev/lib/python3.8/site-packages/binette/main.py", line 512, in main
    contig_to_kegg_counter, contig_to_genes = manage_protein_alignement(
  File "/home/ec2-user/SageMaker/efs/sandbox/sandbox/conda_environments/jolespin/sagemaker/VEBA-binning-prokaryotic_env-dev/lib/python3.8/site-packages/binette/main.py", line 310, in manage_protein_alignement
    io.check_contig_consistency(
  File "/home/ec2-user/SageMaker/efs/sandbox/sandbox/conda_environments/jolespin/sagemaker/VEBA-binning-prokaryotic_env-dev/lib/python3.8/site-packages/binette/io_manager.py", line 209, in check_contig_consistency
    assert are_contigs_consistent, message
AssertionError: 27900 contigs found in file '../../TestData/Assemblies/S1_scaffolds.faa' were not found in assembly_file '../../TestData/Assemblies/S1_scaffolds.fasta'
```

I did my own check and things look good: 

```python
In [3]: import pyfastx

In [5]: contigs_from_assembly = set()
   ...: for id, seq in pyfastx.Fasta("../../TestData/Assemblies/S1_scaffolds.fasta", build_index=False):
   ...:     contigs_from_assembly.add(id)
   ...: contigs_from_proteins = set()

In [6]: for id, seq in pyfastx.Fasta("../../TestData/Assemblies/S1_scaffolds.faa", build_index=False):
   ...:     contigs_from_proteins.add(id.rsplit("_", maxsplit=1)[0])
   ...: 

In [7]: contigs_from_proteins <= contigs_from_assembly
Out[7]: True
```

I've prepended, `S1__` to the contigs and proteins not sure if that causes any errors. 

[S1_sequences.zip](https://github.com/user-attachments/files/18156115/S1_sequences.zip)
[s2b.tar.gz](https://github.com/user-attachments/files/18156154/s2b.tar.gz)

**Comment by JeanMainguy** [comment]
Hi,

Thank you for pointing this out and for providing the test dataset—it was very helpful in identifying the issue.

The problem lies in how Binette handles unbinned contigs from the assembly. Currently, Binette filters out contigs that are not part of any bin set to avoid unnecessary computations (e.g., running Prodigal and Diamond on contigs that are not used in any bins). While this approach saves time, it causes a mismatch when proteins are provided, as unbinned contigs are still included in the protein data. This inconsistency triggers the step that checks for differences between the contigs in the assembly and those associated with the proteins.

In this case, there are 3,324 contigs in input bins, but 31,224 contigs with protein annotations. So, 27,900 contigs are indeed found in the protein file that have been filtered out from the assembly file.

Sorry about that! I’ll patch this soon !

**Comment by jolespin** [comment]
Nice catch!  That's a really smart way to do the backend Pyrodigal run.  Excellent dev work.

**Comment by jolespin** [comment]
Hope your holidays are going well.  Do you happen to have an ETA on when this might get merged into the main branch? I'm in the process of running ~100 samples through this right now.

**Comment by JeanMainguy** [comment]
Hi,

I’m planning to make the release on Monday. I wanted to run a few more checks to ensure everything is solid, but haven’t had the time yet.

The fix is already in the dev branch, so if you need it sooner, you may want to use that in the meantime.

**Comment by JeanMainguy** [comment]
About the contamination weight, I think a value of 2 is a good compromise if you're okay with the contamination going up to 10.

If you'd like to explore how the weight affects your dataset further, you can rerun the analysis with the `--resume` flag and adjust the weight. This way, you won’t need to recompute the more time-consuming steps (like Prodigal and Diamond).

For the resume option to work, make sure Binette can locate the temporary files folder with the intermediate results in the output directory. You could create a symbolic link to it in a new folder, for example.

**Comment by jolespin** [comment]
Thanks for the heads up! I'll give the dev branch a shot on the samples that failed.  Contamination >= 10 should be ok because I'm running a filtering script where move the highest quality genomes for another folder  directory, subset the tables, and prepend a prefix to the bins.

**Comment by JeanMainguy** [comment]
Hi,
I've released the version so this error should no longer occur. 
Don't hesitate to reopen this issue if it doesn't.
